name: 'Sync Template'
description: 'Sync template into a project'
author: 'Thomas Schmelzer'

inputs:
  branch:
    description: 'Branch to sync changes to in the target repo'
    default: 'sync/update-configs'
    required: false
  commit-message:
    description: 'Commit message for sync'
    default: 'chore: sync template'
    required: false
  template-repository:
    description: 'Repository to sync from'
    default: ''
    required: true
  template-branch:
    description: 'Branch to sync from in the template repo'
    default: 'main'
    required: false
  include:
    description: 'List of files and folders to include (multi-line)'
    default: |
      .devcontainer
      .github
      taskfiles
      tests
      .editorconfig
      .gitignore
      .pre-commit-config.yaml
      CODE_OF_CONDUCT.md
      CONTRIBUTING.md
      Makefile
      ruff.toml
      Taskfile.yml
    required: false
  exclude:
    description: 'List of files and folders to exclude (multi-line)'
    default: |
      .git
      README.md
      LICENSE
      action.yml
      .github/workflows/sync.yml
    required: false

runs:
  using: "composite"
  steps:
    - name: Ensure Git repository
      run: |
        git rev-parse --is-inside-work-tree > /dev/null || {
          echo "❌ Not in a git repository"
          exit 1
        }
      shell: bash

    - name: Sparse checkout from template repo
      uses: actions/checkout@v5
      with:
        repository: ${{ inputs.template-repository }}
        path: .template-temp
        ref: ${{ inputs.template-branch }}
        sparse-checkout: ${{ inputs.include }}
        sparse-checkout-cone-mode: false
        fetch-depth: 0

    - name: Apply excludes
      if: ${{ inputs.exclude != '' }}
      working-directory: .template-temp
      shell: bash
      run: |
        ls -all .
        echo "🔍 Processing exclude list..."
        while IFS= read -r item; do
          item="$(echo "$item" | xargs)"
          [ -z "$item" ] && continue
          echo "  Excluding: $item"
          rm -rf "$item"
        done <<< "${{ inputs.exclude }}"
        ls -all .

    - name: Copy template files into target repo
      shell: bash
      run: |
        echo "📂 Copying template files into repo..."
        cp -R .template-temp/* .
        rm -rf .template-temp
        ls -all .
        tree .

    - name: Commit and push changes
      shell: bash
      run: |
        git add -A
        if git diff --cached --quiet; then
          echo "✅ No changes to commit"
          exit 0
        fi
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git commit -m "${{ inputs.commit-message }}"
        
        # Skip push if in test mode
        if [[ "${TEST_MODE}" == "true" ]]; then
          echo "🧪 Test mode enabled, skipping push"
        else
          git push origin "HEAD:${{ inputs.branch }}" --force
        fi
