name: Sync Repository Template
description: Synchronize a repository template into the current project and optionally open a pull request
author: Thomas Schmelzer

inputs:
  token:
    description: GitHub token or PAT for authentication
    required: true

  branch:
    description: Target branch for the sync
    required: false
    default: sync/template-update

  commit-message:
    description: Commit message for the sync
    required: false
    default: "chore: sync template"

  create-pr:
    description: Whether to create a pull request if changes are detected
    required: false
    default: "true"

outputs:
  changes-detected:
    description: Whether changes were detected during the sync (true or false)
    value: ${{ steps.sync.outputs.changes_detected }}

runs:
  using: composite
  steps:

    # ------------------------------------------------------------
    # Checkout target repository
    # ------------------------------------------------------------
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        token: ${{ inputs.token }}
        fetch-depth: 0

    # ------------------------------------------------------------
    # Tooling
    # ------------------------------------------------------------
    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        version: "0.9.17"

    # ------------------------------------------------------------
    # Validate configuration
    # ------------------------------------------------------------
    - name: Validate rhiza configuration
      shell: bash
      run: uvx rhiza validate .

    # ------------------------------------------------------------
    # Materialize + commit changes
    # ------------------------------------------------------------
    - name: Sync template
      id: sync
      shell: bash
      run: |
        set -euo pipefail

        git checkout -B "${{ inputs.branch }}"

        uvx rhiza materialize .

        git add -A

        if git diff --cached --quiet; then
          echo "No changes detected."
          echo "changes_detected=false" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        echo "changes_detected=true" >> "$GITHUB_OUTPUT"

        if git diff --cached --name-only | grep -q '^\.github/workflows/'; then
          echo "⚠️ Workflow files modified — PAT with workflow scope may be required."
        fi

        git config user.name  "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

        git commit -m "${{ inputs.commit-message }}"
        git push origin "HEAD:${{ inputs.branch }}" --force-with-lease

    # ------------------------------------------------------------
    # Create Pull Request
    # ------------------------------------------------------------
    - name: Create pull request
      if: ${{ inputs.create-pr == 'true' && steps.sync.outputs.changes_detected == 'true' }}
      uses: peter-evans/create-pull-request@v8
      with:
        token: ${{ inputs.token }}
        branch: ${{ inputs.branch }}
        delete-branch: false
        title: ${{ inputs.commit-message }}
        body: |
          This pull request synchronizes the repository with its template.

          Changes were generated automatically using **rhiza**.
