name: 'Sync Template'
description: 'Sync template into a project and optionally create a pull request'
author: 'Thomas Schmelzer'

inputs:
  token:
    description: 'GitHub token or PAT for authentication'
    required: true
  source:
    description: 'Path to the YAML configuration file containing template settings'
    required: true
  branch:
    description: 'Target branch in the current repo'
    default: 'sync/update'
  commit-message:
    description: 'Commit message for sync'
    default: 'chore: sync template'
  test-mode:
    description: 'If true, skip push and PR creation'
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Ensure inside a git repository
      shell: bash
      run: git rev-parse --is-inside-work-tree >/dev/null || { echo "❌ Not in a git repository"; exit 1; }

    - name: Parse configuration file
      shell: bash
      id: config
      run: |
        echo "Reading configuration from ${{ inputs.source }}"
        if [ ! -f "${{ inputs.source }}" ]; then
          echo "::error::Configuration file not found: ${{ inputs.source }}"
          exit 1
        fi
        
        # Install yq if not available
        if ! command -v yq &> /dev/null; then
          echo "Installing yq..."
          wget -qO /tmp/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          chmod +x /tmp/yq
          YQ_CMD="/tmp/yq"
        else
          YQ_CMD="yq"
        fi
        
        # Read values from config file
        TEMPLATE_REPO="${{ inputs.template-repository }}"
        if [ -z "$TEMPLATE_REPO" ]; then
          TEMPLATE_REPO=$($YQ_CMD '.template-repository' "${{ inputs.source }}")
          if [ "$TEMPLATE_REPO" = "null" ]; then
            echo "::error::template-repository not found in config file and not provided as input"
            exit 1
          fi
        fi
        echo "template_repository=$TEMPLATE_REPO" >> $GITHUB_OUTPUT
        
        TEMPLATE_BRANCH="${{ inputs.template-branch }}"
        if [ -z "$TEMPLATE_BRANCH" ]; then
          TEMPLATE_BRANCH=$($YQ_CMD '.template-branch // "main"' "${{ inputs.source }}")
        fi
        echo "template_branch=$TEMPLATE_BRANCH" >> $GITHUB_OUTPUT
        
        INCLUDE="${{ inputs.include }}"
        if [ -z "$INCLUDE" ]; then
          INCLUDE=$($YQ_CMD '.include // ""' "${{ inputs.source }}")
        fi
        echo "include<<EOF" >> $GITHUB_OUTPUT
        echo "$INCLUDE" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        
        EXCLUDE="${{ inputs.exclude }}"
        if [ -z "$EXCLUDE" ]; then
          EXCLUDE=$($YQ_CMD '.exclude // ""' "${{ inputs.source }}")
        fi
        echo "exclude<<EOF" >> $GITHUB_OUTPUT
        echo "$EXCLUDE" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Checkout parsed data
      shell: bash
      run: |
        echo "Template repository: ${{ steps.config.outputs.template_repository }}"
        echo "Branch in template:  ${{ steps.config.outputs.template_branch }}"
        echo "Include:\n ${{ steps.config.outputs.include }}"
        echo "Exclude:\n ${{ steps.config.outputs.exclude }}"

    - name: Sparse checkout template
      uses: actions/checkout@v5
      with:
        repository: ${{ steps.config.outputs.template_repository }}
        ref: ${{ steps.config.outputs.template_branch }}
        path: .template-temp
        sparse-checkout: ${{ steps.config.outputs.include }}
        sparse-checkout-cone-mode: false
        fetch-depth: 0
        token: ${{ inputs.token }}
        persist-credentials: 'false'

    - name: Clean template and apply excludes
      shell: bash
      working-directory: .template-temp
      run: |
        echo "Checkout template after sparse checkout"
        ls -all
        rm -rf .git
        [[ -n "${{ steps.config.outputs.exclude }}" ]] && while IFS= read -r item; do
          item="$(echo "$item" | xargs)"
          [ -z "$item" ] || rm -rf "$item" 2>/dev/null || true
        done <<< "${{ steps.config.outputs.exclude }}"
        # tree -L 2 || ls -R

    - name: Commit and optionally push changes
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        TEST_MODE: ${{ inputs.test-mode }}
      run: |
        cp -R .template-temp/. .
        rm -rf .template-temp

        git add -A
        git status
        if git diff --cached --quiet; then
          echo "✅ No changes to commit"
          exit 0
        fi

        # Warn if workflow files are modified
        if git diff --cached --name-only | grep -q "^\.github/workflows/"; then
          echo "⚠️ Workflow files detected. Use PAT with 'workflow' scope."
        fi

        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git commit -m "${{ inputs.commit-message }}"

        # Configure remote with token
        git remote set-url origin "https://x-access-token:${{ inputs.token }}@github.com/${{ github.repository }}.git"

        echo "✅ Remote after reset (masked):"
        git remote -v | sed -E 's@(https://)[^@]+@\\1****@g'

        echo "🔁 Testing ls-remote with this token..."
        git ls-remote --heads origin || echo "❌ ls-remote failed"

        if [[ "${TEST_MODE}" == "true" ]]; then
          echo "🧪 Test mode: skipping push and PR creation"
        else
          echo "🚀 Pushing changes to branch '${{ inputs.branch }}'..."
          if git push origin "HEAD:${{ inputs.branch }}" --force-with-lease; then
            echo "✅ Sync complete"
          else
            echo "⚠️ Push failed. Check permissions."
            exit 1
          fi
        fi

    - name: Create Pull Request (if not in test mode)
      if: ${{ inputs.test-mode != 'true' }}
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ inputs.token }}
        branch: ${{ inputs.branch }}
        commit-message: ${{ inputs.commit-message }}
        title: "chore: sync template from ${{ steps.config.outputs.template_repository }}@${{ steps.config.outputs.template_branch }}"
        body: |
          This PR updates configuration files from
          [${{ steps.config.outputs.template_repository }}@${{ steps.config.outputs.template_branch }}](https://github.com/${{ steps.config.outputs.template_repository }}/tree/${{ steps.config.outputs.template_branch }}).
